[SUREFIRE-500] puzzling NoClassDefFoundError instead of meaningfull stacktrace
Fixed with integration test

git-svn-id: https://svn.apache.org/repos/asf/maven/surefire/trunk@1058735 13f79535-47bb-0310-9956-ffa450edef68