[SUREFIRE-1882] Fix failures when compiled on Java 9+ and run on Java 8
* [SUREFIRE-1882] Fix failures when compiled on Java 9+ and run on Java 8

Cast to Buffer to avoid java.lang.NoSuchMethodError due to JDK API
breakage.

This was fixed in a similar way in apache/maven-wagon@92c0d2a.

See mongodb/mongo-java-driver@21c91bd for details.

* [SUREFIRE-1882] Minor code review finding

Use Buffer instead of ByteBuffer in method StatelessXmlReporterTest.testSyncOnDeferredFile() in order to avoid casts and still be compatible with JDK 8.