[SUREFIRE-1762] skipAfterFailureCount>0 with testng 7.1.0 resulting in java.lang.NoSuchMethodError: org.testng.TestNG.addListener(Lorg/testng/ITestListener;)V
* instead of org.testng.TestNG.addListener(org.testng.ITestListener) which
  has been removed from testng 7.x+ (SUREFIRE-1762)
* instead of org.testng.TestNG.addListener(java.lang.Object) which is
  deprecated in testng 7.x+