Revert "[SUREFIRE-1762] skipAfterFailureCount>0 with testng 7.1.0 resulting in java.lang.NoSuchMethodError: org.testng.TestNG.addListener(Lorg/testng/ITestListener;)V"
This reverts commit 5534bd7590af1e3ff8b7706e788a1c2214e70141.