MIME type for javascript is now officially application/javascript  mime js from text/javascript to application/javascript
https://stackoverflow.com/questions/189850/what-is-the-javascript-mime-type-for-the-type-attribute-of-a-script-tag

"This is a common mistake. The MIME type for javascript wasn't standardized for years. It's now officially: "application/javascript"."
http://www.rfc-editor.org/rfc/rfc4329.txt
https://github.com/apache/maven-surefire/pull/188

ain/java/org/apache/maven/plugins/surefire/report/SurefireReportGenerator.java
@@ -78,7 +78,7 @@ public void doGenerateReport( LocalizedProperties bundle, Sink sink )
        atts.addAttribute( TYPE, "text/javascript" );
        atts.addAttribute( TYPE, "application/javascript" );

 Please run the build locally. You will see this error
 testWithIdenticalNames(org.apache.maven.surefire.its.jiras.Surefire260TestWithIdenticalNamesIT):
 ReferenceError: "toggleDisplay" is not defined. (javascript url#184)
 I am not sure if this is the only one.
 Feel free to run the build like this mvn install -P run-its. See the README. There are instructions to use JDK8+.
 Do not worry if it takes one hour to complete.
 One hint, do not overload the PC with other tasks. The build has performance tests and if the delays are paused by overloaded CPU, other tests fail.
 Squash all changes in one commit.

>>>>>
 https://www.w3schools.com/tags/tag_script.asp
 Differences Between HTML and XHTML

 In XHTML, the content inside scripts is declared as #PCDATA (instead of CDATA), which means that entities will be parsed.

 This means that in XHTML, all special characters should be encoded, or all content should be wrapped inside a CDATA section

https://maven.apache.org/surefire/maven-surefire-report-plugin/surefire-report.html